name: bkash_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.0.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.4.2

  animated_bottom_navigation_bar: ^1.3.0
  curved_navigation_bar: ^1.0.3
  google_nav_bar: ^5.0.6
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/applogo3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/lottie/
